### PR TITLE
feature: Add support for buildTarget/jvmCompileClasspath

### PR DESCRIPTION
**Pull request by tgodzik**
Previously, classpath would be obtained via scalacOptions and javacOptions requests, which would cause additional querries even if client was only interested in actual javac/scalac options.

Now, we don't send classpath together with scalac/javac options if the client declares that they will use the new jvmCompileClasspath request, which they should then trigger.

Integration tests blocked on https://github.com/build-server-protocol/bsp-testkit2/pull/43

### CODE REVIEW

**Comment by tgodzik** [comment]
> code-wise looks good, but i'll have to test (next week) it with our plugin - we still use classpath for local executions

Unless the client specifies `compileClasspathReceiver` nothing should change, so ideally nothing should break for Intellij plugin

**Comment by tgodzik** [comment]
Any chance for someone to take a look at this or the other PRs?

**Review by agluszak — APPROVED** [review]

**Comment by agluszak** [comment]
@tgodzik I accepted the changes, please resolve conflicts

**Comment by tgodzik** [comment]
> @tgodzik I accepted the changes, please resolve conflicts

Thanks! I rebased and added a note to the changelog

**Pull request merged**
