### PR TITLE
[fix] Fixup failed target names from BEP in bazel 6+

### PR DESCRIPTION
**Pull request by steveniemitz**
Target names in BEP in bazel 6 aren't prefixed with `@`, which causes a mismatch in comparing the failed targets with project targets.

### CODE REVIEW

**Review by abrams27 — APPROVED** [review]
thanks a lot, please update the changelog

i have also another thing to u: we were thinking that this is not the best place for bloop support - we dont know bloop well (so it's difficult to maintain it), and it actually doesnt use that much from our codebase - the bazel-bsp server doesnt even exist in the bloop mode;

since bazel-bsp can be used as a maven dependency, we have 2 propositions:
- move it to a completely separate repo (not under jetbrains)
- move it to the bloop itself
what do u think about it?

**Comment by steveniemitz** [comment]
> move it to a completely separate repo (not under jetbrains)

I could get behind this.  Agreed its not really sharing much from bazel-bsp that couldn't be just exposed as APIs.

**Comment by abrams27** [comment]
perfect, then we will deprecate it in the following release, we are planning to release 3.0 with breaking changes around bsp notifications and project view in next ~2 months 

can i merge this pr?

**Comment by steveniemitz** [comment]
yeah this is good to merge.  It looks like the google-format failure was unrelated to this change.

Deprecation for 3.0 seems fine to me, I'll figure out a better place for it.

**Comment by abrams27** [comment]
fyi: we are planning to do the 3.0 release next week (or the following one) - it will also remove bloop from bazel-bsp

cc @lukaszwawrzyk

**Pull request merged**
